html $ do
    H.head $ do
        meta ! httpEquiv "Content-Type" ! content "text/html; charset=UTF-8"
        H.title "My Hakyll Blog - $title$"
        link ! rel "stylesheet" ! type_ "text/css" ! href "/css/default.css"
        link ! rel "stylesheet" ! type_ "text/css" ! href "/css/main.css"
    body $ do
        H.div ! A.id "header" $ do
            H.div ! A.id "logo" $ a ! href "/" $ "My Hakyll Blog"
            H.div ! A.id "navigation" $ do
                a ! href "/" $ "Home"
                a ! href "/about.html" $ "About"
                a ! href "/contact.html" $ "Contact"
                a ! href "/archive.html" $ "Archive"
        H.div ! A.id "content" $ do
            h1 "$title$"
            "$body$"
        H.div ! A.id "footer" $ do
            "Site proudly generated by"
            a ! href "http://jaspervdj.be/hakyll" $ "Hakyll"

